# .github/workflows/build.yml
name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: sonarcloud
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      # Simulación de un build (podría ser más elaborado en un proyecto real)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      # Paso de despliegue
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .
